function M_data = f_struct_set(num_mt_tmp)

M_data    = [];
data      = [];

for i=1 : num_mt_tmp
    microtrip{i} = i;
end

type      = {'const', 'maps'};
%Set map variales here
maps      = {'map_mileage_all',  'map_mileage_mt',  'map_vspe',        ... 
             'map_stptime',      'map_acctime',     'map_statime',     ... 
             'map_dectime',      'map_dvsp_x_vsp',  'map_dvsp_y_dvsp', ...
             'map_dvsp',         'map_dvsp_dec',    'map_dvsp_sta',    ...
             'map_dvsp_acc',     'map_acctime',     'map_statime',     ...
             'map_dectime'};

M_data    = struct('microtrip', microtrip, 'type',     ...
            struct('type',      type,      'maps',    ...
            struct('maps',      maps,      'data',     ...
            struct('data',      data))));
end
        