function M_data = fnames_filednames(num_mt_tmp)

M_data    = [];
data      = [];

for i=1 : num_mt_tmp
    microtrip{i} = i;
end

type      = {'var', 'as'};
%Set amount of radar targets here
target    = {'ego',     'track1',  'track2',  'track3',  'track4',  ... 
             'track5',  'track6',  'track7',  'track8',  'track9',  ... 
             'track10', 'track11', 'track12', 'track13', 'track14', ...
             'track15', 'track16', 'lead',    'env'};
%Set list of variables you want to observe here
variable  = {'posx',      'speedx',        'accelx',        'jerkx',        'ILV',        ...
             'thw',       'ttc',           'thw_inv',       'ttc_inv',      'ttc_delta',  ...
             'thw_delta', 'ttc_delta_inv', 'thw_delta_inv', 'apo',          'bksw',       ... 
             'swa',       'posy',          'curve',         'lat_dist',     'width',      ...
             'latitude',  'longitude'};

%ILV status data
ilv       = {'non_ilv', 'ilv'};

M_data    = struct('microtrip', microtrip, 'type',     ...
            struct('type',      type,      'target',   ...
            struct('target',    target,    'variable', ...  
            struct('variable',  variable,  'ilv',      ...
            struct('ilv',       ilv,       'data',     ...
            struct('data',      data))))));
        
